config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root to: 'hotels#index'
	resources :hotels, only: [:index, :new, :create]

	resources :states, only: :index
	resources :cities, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
  	belongs_to :user
  	has_many :facility_hotels
  	has_many :hotels, through: :facility_hotels

  	default_scope -> {order(:name)}

  	validates :name, presence: true
  	validates :name, uniqueness: true

  	def self.select_list
  		all.map{|f| [f.name, f.id]}.uniq{|f| f.first}
  	end
end

app/models/facility_hotel.rb
class FacilityHotel < ApplicationRecord
  	belongs_to :hotel
  	belongs_to :facility
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  	belongs_to :user
  	has_many :facility_hotels
  	has_many :facilities, through: :facility_hotels

  	validates :name, :price, :country, :state, :city, :address, presence: true

  	def self.filters select_facilities, select_country, select_state, select_city, min_price, max_price, text
  		if select_facilities.blank? and select_country.blank? and select_state.blank? and select_city.blank? and min_price.blank? and max_price.blank?
  			all.includes(facility_hotels: :facility)
  		else
  			hotels = []
  			any_filter = false
  			if !select_city.blank?
  				hotels = where(city: select_city, country: select_country, state: select_state).includes(facility_hotels: :facility)
  				any_filter = true
  			elsif !select_state.blank? and !any_filter
  				hotels = where(country: select_country, state: select_state).includes(facility_hotels: :facility)
  				any_filter = true
  			elsif !select_country.blank? and !any_filter
  				hotels = where(country: select_country).includes(facility_hotels: :facility)
  				any_filter = true
  			end
  			
  			if !select_facilities.blank?
  				if hotels.empty? and !any_filter
  					hotels = joins(facility_hotels: :facility).where(facility_hotels: {facility: select_facilities}).includes(facility_hotels: :facility)
  				else
  					hotels = hotels.joins(facility_hotels: :facility).where(facility_hotels: {facility: select_facilities}).includes(facility_hotels: :facility)
  				end
  				any_filter = true
  			end

  			if !min_price.blank? or !max_price.blank?
  				q = ""
  				q += "price >= #{min_price}" if !min_price.blank?
  				q += " AND price <= #{max_price}" if !max_price.blank?
  				if hotels.empty? and !any_filter
  					hotels = where(q).includes(facility_hotels: :facility) if !q.blank?
  				else
  					hotels = hotels.where(q).includes(facility_hotels: :facility) if !q.blank?
  				end
  				any_filter = true if !hotels.empty?
  			end

  			if !text.blank?
  				if hotels.empty? and !any_filter
  					hotels = where("hotels.name ILIKE ?", "%#{text}%").includes(facility_hotels: :facility)
  				else
  					hotels = hotels.where("hotels.name ILIKE ?", "%#{text}%").includes(facility_hotels: :facility)
  				end
  				any_filter = true
  			end

	  		hotels.uniq
	  	end
  	end
end

app/models/user.rb
class User < ApplicationRecord
  	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
	has_many :hotels
	has_many :facilities

	enum role: [:ordinary, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def index
		@cities = CS.get(params[:country], params[:state])
		respond_to :js
	end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :has_permission, only: [:new, :create]
	before_action :filters, only: [:index, :new, :create]

	# GET
	def index
		@hotels = Hotel.filters(params[:select_facilities], params[:select_coutry], params[:select_state], params[:select_city], params[:min_price], params[:max_price], params[:text])
	end

	# GET
	def new
		@hotel = Hotel.new
	end

	# POST
	def create
		@hotel = Hotel.new(hotel_params.merge(user: current_user, country: params[:select_coutry], state: params[:select_state], city: params[:select_city]))
		respond_to do |format|
      		if @hotel.save
      			params[:hotel][:facilities].reject!{ |c| c.blank? }.each{|f| FacilityHotel.create(facility_id: f.to_i, hotel: @hotel)}
        		format.html { redirect_to hotels_path, notice: 'Success' }
      		else
        		format.html { render :new }
      		end
    	end
	end

	private
		def has_permission
			unless current_user.admin?
				respond_to do |format|
				    format.html do
				      render file: "#{Rails.root}/public/403.html",
				      layout: false, status: 403
				    end
				end and return
			end
		end

		def filters
			@countries = CS.countries.map { |c| [c[1], c[0]] }
			@facilities = Facility.select_list
		end

		def hotel_params
			params.require(:hotel).permit(:name, :price, :address)
		end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

	def index
	   	@states = CS.states(params[:country])
	   	respond_to :js
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/index.js.erb
// Find the state select box
var city = document.getElementById("select_city");

// Clear the options in the select box
while (city.firstChild) city.removeChild(city.firstChild);

// Add a placeholder
var placeholder = document.createElement("option");
placeholder.text = "Choose a city";
placeholder.value = "";
city.appendChild(placeholder);

// Add the states
<% @cities.each do |c| %>
    city.options[city.options.length] = new Option('<%= c %>');
<% end %>

app/views/hotels/_form.html.erb
<%= form_for hotel, url: (hotel.id.nil? ? hotels_path : hotel_path(hotel.id)), method: (hotel.id.nil? ? :post : :put) do |form| %>
    <% if hotel.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(hotel.errors.count, "error") %>:</h2>

        <ul>
            <% hotel.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="row">
        <div class="col-md-12">            
            <div class="form-group">
                <label class="form-control-label">Name</label>
                <%= form.text_field :name, class: "form-control", placeholder: "Name", required: true %>
            </div>

            <div class="form-group">
                <label class="form-control-label">Individual Price</label>
                <%= form.number_field :price, class: "form-control", placeholder: "Price", required: true %>
            </div>

            <div class="form-group">
                <label class="form-control-label">Country</label>
                <%= select_tag(:select_coutry, options_for_select(@countries), {class: "form-control", required: true} )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">State</label>
                <%= select_tag(:select_state, options_for_select([]), {class: "form-control", required: true} )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">City</label>
                <%= select_tag(:select_city, options_for_select([]), {class: "form-control", required: true} )%>
            </div>

            <div class="form-group">
                <label class="form-control-label">Address</label>
                <%= form.text_field :address, class: "form-control", placeholder: "Address", required: true %>
            </div>
            

            <div class="form-group">
                <label class="form-control-label">Facilities</label>
                <%= form.select(:facilities, @facilities, {},{multiple: true, class: "form-control", required: true} )%>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="form-group">
                <%= form.submit "Submit", class: "btn btn-lg btn-info btn-block" %>
            </div>
        </div>
    </div>

<% end %>

app/views/hotels/index.html.erb
<div class="row">
	<!-- FILTERS -->
	<aside class="col-md-3">
		<form class="form-header" action="<%= root_path %>" method="GET">
			<div class="form-group">
                <label class="form-control-label">Quantity</label>
                <%= select_tag(:quantity, options_for_select(1..100, params[:quantity]) , class: "form-control" )%>
            </div>
			<div class="form-group">
                <label class="form-control-label">Facilities</label>
                <%= select_tag(:select_facilities, options_for_select(@facilities,params[:select_facilities]), {multiple: true, class: "form-control"})%>
            </div>
            <div class="form-group">
                <label class="form-control-label">Country</label>
                <%= select_tag(:select_coutry, options_for_select(@countries, params[:select_coutry]), {include_blank: true, class: "form-control"} )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">State</label>
                <%= select_tag(:select_state, options_for_select([], params[:select_state]), {class: "form-control"} )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">City</label>
                <%= select_tag(:select_city, options_for_select([], params[:select_city]), {class: "form-control"} )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">Min Price</label>
                <%= number_field_tag(:min_price, params[:min_price], class: "form-control" )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">Max Price</label>
                <%= number_field_tag(:max_price, params[:max_price], class: "form-control" )%>
            </div>
            <div class="form-group">
                <label class="form-control-label">Name</label>
                <%= text_field_tag(:text, params[:text], class: "form-control" )%>
            </div>

            <div class="form-group">
            	<input type="submit" name="submit" class="form-control btn btn-success">
            </div>
		</form>
	</aside>

	<!-- RESULTS -->
	<div class="col-md-9">
		<% unless @hotels.empty? %>
			<table class="table table-bordered">
			    <thead>
			      	<tr>
			        	<th>Name</th>
			        	<th>Facilities</th>
			        	<th>City</th>
			        	<th>Individual Price</th>
			        	<th>Total Price</th>
			      	</tr>
			    </thead>
			    <tbody>
			    	<% @hotels.each do |hotel| %>
				      	<tr>
				        	<td><%= hotel.name %></td>
				        	<td><%= hotel.facilities.map{|f| f.name}.to_sentence%></td>
				        	<td><%= hotel.city %></td>
				        	<td><%= number_to_currency(hotel.price) %></td>
				        	<td><b><%= number_to_currency(hotel.price * params[:quantity].to_f) %></b></td>
				      	</tr>
			      	<% end %>
			    </tbody>
			 </table>
		<% else %>
			<h1>No Hotel Found :(</h1>
		<% end %>
	</div>	
</div>

app/views/hotels/new.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>New Hotel</h1>
		<%= render "form", hotel: @hotel%>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>VisitProject</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Visit Project</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <% if current_user.nil? %>
                            <li><a href="<%= new_user_session_path %>">Login</a></li>
                        <% else %>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<%= new_hotel_path %>">+ New Hotel</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <%= link_to destroy_user_session_path, method: :delete do %>
                                            Logout
                                        <%end%>
                                    </li>
                                </ul>
                            </li>
                        <% end %>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h3><%= notice %></h3>
                    <h3><%#= flash %></h3>                    
                    <%= yield %>
                </div>                
            </div>
        </div>
        
    </body>
</html>

app/views/states/index.js.erb
// Grab the state select box.
var state = document.getElementById("select_state");

// Clear any populated options in the select box
while (state.firstChild) state.removeChild(state.firstChild);

// Add a placeholder
var placeholder = document.createElement("option");
placeholder.text = "Choose a state";
placeholder.value = "";
state.appendChild(placeholder);

// Use erb templating to add the states
<% @states.each do |s| %>
  	state.options[state.options.length] = new Option('<%= s[1] %>', '<%= s[0] %>')
<% end %>